banking_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ASWYXEI-QW06929
      user: admin
      password: Bablu7020967247
      role: ACCOUNTADMIN
      database: BANKING_DWH
      warehouse: COMPUTE_WH
      schema: STAGING
      threads: 4
